
import { Reservation, ReservationStatus, TransmissionType } from './types';

// Helper function to format MM/DD/YYYY to YYYY-MM-DD
function formatDate(dateStr: string): string {
    const parts = dateStr.split('/');
    if (parts.length === 3) {
        // Assuming MM/DD/YYYY
        return `${parts[2]}-${parts[0].padStart(2, '0')}-${parts[1].padStart(2, '0')}`;
    }
    return dateStr; // fallback for other formats
}

export const importedReservations: Reservation[] = [
  {
    id: "res-import-1",
    personName: "Longdy yi",
    bookingId: "D012958655-Q5X9",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/06/2026"),
    startDate: "2026-02-06T14:00",
    endDate: "2026-02-10T10:00",
    reservationVehicle: "CDAR",
    carModel: "KIA Pegas",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 48,
    amount: 48,
    createdBy: "res user"
  },
  {
    id: "res-import-2",
    personName: "Jeong kyu",
    bookingId: "D012823793-3VY2",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/04/2026"),
    startDate: "2026-02-06T03:00",
    endDate: "2026-02-08T18:00",
    reservationVehicle: "SDAR",
    carModel: "Nissan Sentra",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CANCELLED,
    baseAmount: 54,
    amount: 54,
    createdBy: "res user"
  },
  {
    id: "res-import-3",
    personName: "Amira gerasimova",
    bookingId: "CJT-199275457",
    source: "Car Jet",
    locationName: "airport branch",
    bookingDate: formatDate("02/03/2026"),
    startDate: "2026-02-07T10:30",
    endDate: "2026-02-12T02:00",
    reservationVehicle: "CDAR",
    carModel: "MGzs",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 60,
    amount: 60,
    createdBy: "res user"
  },
  {
    id: "res-import-4",
    personName: "Adrian morales",
    bookingId: "D012902911-MHYY",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("01/31/2026"),
    startDate: "2026-02-07T03:30",
    endDate: "2026-02-15T00:00",
    reservationVehicle: "EGDR",
    carModel: "MGzs",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 189,
    amount: 189,
    createdBy: "res user"
  },
  {
    id: "res-import-5",
    personName: "Nawal anbar",
    bookingId: "D012950572-YHGN",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/07/2026"),
    startDate: "2026-02-07T10:30",
    endDate: "2026-02-13T22:00",
    reservationVehicle: "CFMR",
    carModel: "Nissan Kicks",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 140,
    amount: 140,
    createdBy: "res user"
  },
  {
    id: "res-import-6",
    personName: "Iuca feri",
    bookingId: "D012913509-HSJE",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/01/2026"),
    startDate: "2026-02-07T13:00",
    endDate: "2026-02-10T08:00",
    reservationVehicle: "CDAR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 36,
    amount: 36,
    createdBy: "res user"
  },
  {
    id: "res-import-7",
    personName: "Selcuk kicirgan",
    bookingId: "D012959595-HKJ6",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/06/2026"),
    startDate: "2026-02-07T06:00",
    endDate: "2026-02-11T09:00",
    reservationVehicle: "CDAR",
    carModel: "Nissan Sentra",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 65,
    amount: 100.5,
    createdBy: "res user"
  },
  {
    id: "res-import-8",
    personName: "Hussnain aziz",
    bookingId: "D012881850-MXMX",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("01/29/2026"),
    startDate: "2026-02-01T16:30",
    endDate: "2026-02-07T15:00",
    reservationVehicle: "CDMR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 66,
    amount: 66,
    createdBy: "res user"
  },
  {
    id: "res-import-9",
    personName: "Tadhg Concannon",
    bookingId: "CJT-197246157",
    source: "Car Jet",
    locationName: "airport branch",
    bookingDate: formatDate("01/10/2026"),
    startDate: "2026-02-07T17:00",
    endDate: "2026-02-10T13:30",
    reservationVehicle: "EGDR",
    carModel: "JACs3",
    transmission: TransmissionType.AUTOMATIC,
    notes: "447485000000",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 78,
    amount: 99.3,
    createdBy: "res user"
  },
  {
    id: "res-import-10",
    personName: "Adrian pomaga",
    bookingId: "CJT-199374880",
    source: "Car Jet",
    locationName: "airport branch",
    bookingDate: formatDate("02/04/2026"),
    startDate: "2026-02-05T08:30",
    endDate: "2026-02-07T11:30",
    reservationVehicle: "ECAR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.AUTOMATIC,
    notes: "40761175876",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 36,
    amount: 36,
    createdBy: "res user"
  },
  {
    id: "res-import-11",
    personName: "Zakaria hamitou",
    bookingId: "CJT-197071057",
    source: "Car Jet",
    locationName: "airport branch",
    bookingDate: formatDate("01/07/2026"),
    startDate: "2026-02-02T23:00",
    endDate: "2026-02-08T09:00",
    reservationVehicle: "FVMR",
    carModel: "Hyundai H1",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 252,
    amount: 252,
    createdBy: "res user"
  },
  {
    id: "res-import-12",
    personName: "Kazumi sakakibara",
    bookingId: "D012890517-5F7E",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("01/30/2026"),
    startDate: "2026-02-07T10:30",
    endDate: "2026-02-09T13:30",
    reservationVehicle: "CDAR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.NO_SHOW,
    baseAmount: 36,
    amount: 36,
    createdBy: "res user"
  },
  {
    id: "res-import-13",
    personName: "Numan hasan",
    bookingId: "CJT-199501967",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/06/2026"),
    startDate: "2026-02-07T04:30",
    endDate: "2026-02-12T08:00",
    reservationVehicle: "EDAR",
    carModel: "KIA Pegas",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.NO_SHOW,
    baseAmount: 72,
    amount: 72,
    createdBy: "res user"
  },
  {
    id: "res-import-14",
    personName: "Martin lukas",
    bookingId: "D012908704-jh4g",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/01/2026"),
    startDate: "2026-02-08T11:00",
    endDate: "2026-02-13T18:00",
    reservationVehicle: "CDAR",
    carModel: "KIA Pegas",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 72,
    amount: 72,
    createdBy: "res user"
  },
  {
    id: "res-import-15",
    personName: "Hyesook kim",
    bookingId: "D012901728-VQ7F",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("01/31/2026"),
    startDate: "2026-02-08T04:30",
    endDate: "2026-02-10T11:00",
    reservationVehicle: "IDMR",
    carModel: "Kia Cerato",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 51,
    amount: 51,
    createdBy: "res user"
  },
  {
    id: "res-import-16",
    personName: "Ahmad abdelaal",
    bookingId: "D012938488-C9R2",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/04/2026"),
    startDate: "2026-02-08T08:30",
    endDate: "2026-02-13T20:30",
    reservationVehicle: "CDAR",
    carModel: "KIA Pegas",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 72,
    amount: 72,
    createdBy: "res user"
  },
  {
    id: "res-import-17",
    personName: "Dennis schleppi",
    bookingId: "ECD83E12",
    source: "Economy Car Rental",
    locationName: "airport branch",
    bookingDate: formatDate("02/05/2026"),
    startDate: "2026-02-08T15:30",
    endDate: "2026-02-12T15:30",
    reservationVehicle: "",
    carModel: "KIA Pegas",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 43,
    amount: 43,
    createdBy: "res user"
  },
  {
    id: "res-import-18",
    personName: "Rafal hadas",
    bookingId: "CJT-199542257",
    source: "Car Jet",
    locationName: "airport branch",
    bookingDate: formatDate("02/07/2026"),
    startDate: "2026-02-08T13:30",
    endDate: "2026-02-11T11:00",
    reservationVehicle: "ECMR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 33,
    amount: 33,
    createdBy: "res user"
  },
  {
    id: "res-import-19",
    personName: "Mohammad ashfaq",
    bookingId: "D012965914-5JMK",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/07/2026"),
    startDate: "2026-02-08T16:30",
    endDate: "2026-02-12T14:30",
    reservationVehicle: "IDAR",
    carModel: "MG 5",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 60,
    amount: 60,
    createdBy: "res user"
  },
  {
    id: "res-import-20",
    personName: "Numan hasan",
    bookingId: "CJT-199600817",
    source: "Car Jet",
    locationName: "airport branch",
    bookingDate: formatDate("02/08/2026"),
    startDate: "2026-02-08T16:00",
    endDate: "2026-02-12T08:00",
    reservationVehicle: "EDAR",
    carModel: "KIA Pegas",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 48,
    amount: 48,
    createdBy: "res user"
  },
  {
    id: "res-import-21",
    personName: "Ali baadoud",
    bookingId: "D012971012-2E7G",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/07/2026"),
    startDate: "2026-02-08T15:00",
    endDate: "2026-02-15T14:00",
    reservationVehicle: "EDAR",
    carModel: "KIA Pegas",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 84,
    amount: 84,
    createdBy: "res user"
  },
  {
    id: "res-import-22",
    personName: "Talal arandi",
    bookingId: "D012945925-UQCB",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/04/2026"),
    startDate: "2026-02-05T03:30",
    endDate: "2026-02-09T17:30",
    reservationVehicle: "CDAR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 60,
    amount: 60,
    createdBy: "res user"
  },
  {
    id: "res-import-23",
    personName: "Hasan alwawi",
    bookingId: "D012944573-HLED",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/05/2026"),
    startDate: "2026-02-05T03:30",
    endDate: "2026-02-09T15:00",
    reservationVehicle: "CDAR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 60,
    amount: 95.25,
    createdBy: "res user"
  },
  {
    id: "res-import-24",
    personName: "Mohammad farajallah",
    bookingId: "EC77D679",
    source: "Economy Car Rental",
    locationName: "airport branch",
    bookingDate: formatDate("02/07/2026"),
    startDate: "2026-02-09T05:00",
    endDate: "2026-02-12T11:00",
    reservationVehicle: "CCMR",
    carModel: "KIA Pegas",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 46,
    amount: 46,
    createdBy: "res user"
  },
  {
    id: "res-import-25",
    personName: "Ezra septimus",
    bookingId: "D012978724-R3Q2",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/08/2026"),
    startDate: "2026-02-09T21:00",
    endDate: "2026-02-18T02:00",
    reservationVehicle: "CDMR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 99,
    amount: 99,
    createdBy: "res user"
  },
  {
    id: "res-import-26",
    personName: "Ahmad abusal",
    bookingId: "D012983596-P5H9",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("02/08/2026"),
    startDate: "2026-02-09T14:00",
    endDate: "2026-02-15T20:00",
    reservationVehicle: "CDAR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 84,
    amount: 84,
    createdBy: "res user"
  },
  {
    id: "res-import-27",
    personName: "Mohammad alzoubi",
    bookingId: "D012895338-FP2G",
    source: "Discover Car Hire",
    locationName: "airport branch",
    bookingDate: formatDate("01/30/2026"),
    startDate: "2026-02-05T09:00",
    endDate: "2026-02-07T20:00",
    reservationVehicle: "CDAR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.AUTOMATIC,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 36,
    amount: 36,
    createdBy: "res user"
  },
  {
    id: "res-import-28",
    personName: "Belal alhuniti",
    bookingId: "ECB19339",
    source: "Economy Car Rental",
    locationName: "airport branch",
    bookingDate: formatDate("02/04/2026"),
    startDate: "2026-02-05T09:00",
    endDate: "2026-02-07T12:00",
    reservationVehicle: "ECMR",
    carModel: "Nissan Sunny",
    transmission: TransmissionType.MANUAL,
    notes: "",
    status: ReservationStatus.CONFIRMED,
    baseAmount: 32,
    amount: 32,
    createdBy: "res user"
  }
];
